name: CI météo

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

jobs:   # <-- OBLIGATOIRE
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - run: PYTHONPATH=. pytest

  docker:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - run: docker build -t weather-app .

  push-docker:   # <-- ton job doit être défini ICI
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - uses: actions/checkout@v3
      - run: echo "${{ secrets.Sugitha17! }}" | docker login -u "${{ secrets.Sugitha}}" --password-stdin
      - run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/weather-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/weather-app:latest
